- name: Disable seLinux
  selinux: 
    policy: targeted 
    state: disabled

- name: Disable transparent huge pages until reboot
  shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled && echo never > /sys/kernel/mm/transparent_hugepage/defrag
  ignore_errors: true

- name: Disable IPv6 with sysctl
  sysctl: name={{ item }} value=1 state=present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: sysctl -p
  shell:  sysctl -p

- name: Be sure firewalld is disabled
  systemd: name=firewalld enabled=no

- name: Remove firewalld
  package:
    name: firewalld
    state: absent
